iLCSoft/CLICPerformance

examples/clicReconstruction.xml
values for resolution in u and v fixed in the endcap digitisers
=> Options steer

examples/PandoraSettings/PandoraSettingsDefault.xml
- Reconstruction::MuonReco: adapt more parameters to new geometry, as recommended by @bonoxu
=> Reconstruction::MuonReco: more parameters adapted for new yoke geometry

Tracking/include/ClicEfficiencyCalculator.h, Tracking/src/ClicEfficiencyCalculator.cc, examples/clicReconstruction.xml
- ClicEfficiencyCalculator: Added number of hits on track to the simplified tree output
- Reconstruction: Updated parameters for the ConformalTracking
=> Updated conformal tracking parameters 

examples/clicReconstruction.xml
Still missing the XLoose variables for lower energy reconstruction
- Add PFOSelector processors, copied from CDR reconstruction
=> Add running of PFOSelector Default/Tight/Loose, options copied from cdr version

Calorimetry/src/ShowerStudy.cxx, Tracking/src/ClicEfficiencyCalculator.cc, Tracking/src/HitResiduals.cc, Tracking/src/TrackChecker.cc
- Adapt to the rest of namespace changes in DD4hep
=> Adapt to the rest of namespace changes in DD4hep

etc/extra-root.supp
- Add suppressions for root things, lcio buffers etc.
=> Valgrind Suppressions

examples/clicReconstruction.xml
Tuning, calibration, and validation still necessary for both processors
- Add LumiCalReco processor
- Add BeamCalReco processor
=> Add FCal Reconstruction Processors

examples/clicReconstruction.xml
- Add processor printing out current event number
- overlay: add parameters for 380GeV
- overlay: change Number of BX to overlay to 30 fitting the time interval
=> Event number printout, overlay for 380 GeV

examples/clicReconstruction.xml, source/Conditions/include/CLICRecoConfig.h
- Overlay processors now in a group to avoid duplicating parameters
- Add overlay parameters for 350, 420, 500, and 1.4TeV
=> Overlay processors now in a group to avoid duplicating parameters

examples/clicReconstruction.xml, source/Conditions/include/CLICRecoConfig.h, source/Conditions/src/CLICRecoConfig.cc
* CLICRecoConfig: Updated Config for Tracking: Truth, ConformalPlusExtrapolator, Conformal
=> CLICRecoConfig: Updated Config for Tracking: Truth, ConformalPlusExtrapolator, Conformal

Tracking/src/ClicEfficiencyCalculator.cc, Tracking/src/HitResiduals.cc, Tracking/src/TrackChecker.cc
- CLICEfficiency/HitResiduals/TrackChecker: use streamlog instead of cout
=> use streamlog

Tracking/include/TrackChecker.h, Tracking/src/TrackChecker.cc
- TrackChecker: added MCParticle PDG info in checktree
=> TrackChecker: added MCParticle PDG info in checktree

Tracking/src/ClicEfficiencyCalculator.cc, Tracking/src/TrackChecker.cc
- Drop unused and no longer existing header includes AidaSoft/DD4hep#241
=> Remove include of removed file

examples/clicReconstruction.xml
Updated parameters for Conformal Tracking in clicReconstruction.xml
- ThetaRange: from 0.03 to 0.05
- MinClustersOnTrack: from 6 to 4
- MaxChi2: from 50 to 100
=> Updated Conformal Tracking parameters in clicReconstruction.xml

examples/clic_steer.py, examples/lcio_geant4.py
- Update field stepping to Geant4 defaults
=> Update field stepping to Geant4 defaults

examples/clicReconstruction.xml
- Reconstruction: add subClusterEnergyID to LumiCalReco and BeamCalReco
=> Reconstruction: LumiCal/BeamCal: add subClusterEnergyID parameter

examples/clicReconstruction.xml
- Reconstruction: add overlay for 3TeV L*=6m layout
=> CLIC Reconstruction: add overlay for 3TeV L*=6m layout

Flavour_tagging/Flavtag_performance.C, Flavour_tagging/Job_example.py, Flavour_tagging/README.md, Flavour_tagging/training.xml, Flavour_tagging/vtx_makentp.xml
As promised, 
- Code to run the flavour-tagging training and produce performance plots. 
Cheers,
Nacho
=> Folder for Flavour-tagging performance tests

Tracking/include/ClicTrackingValidate.h, Tracking/src/ClicTrackingValidate.cc
- Tracking/include(src)/ClicTrackingValidate.h(cc)
- Processor to validate the tracking using MCParticle information at particle and hit level
- Checks the misassociated hits (from wrong MCParticle) and the missed hits
=> ClicTrackingValidate: processor to validate the tracking at particle and hit level

clicConfig/clicReconstruction.xml, fcceeConfig/fccReconstruction.xml
- clicReconstruction.xml and fccReconstruction.xml: setup the configuration for ConformalTrackingV2
- parameters match the configuration of old ConformalTracking
- NB: parameters for clic and fcc are supposed to be different
=> steering files: configuration for ConformalTrackingV2

clicConfig/clicReconstruction.xml
- Added VertexFinder to default clicReconstruction steering file. Relates to #68
=> Added vertexing to default clicReconstruction steering file

fcceeConfig/fccReconstruction.xml
- FCCee reconstruction: update track selection cuts (d0, z0, hit radius) to 200mm
=> Update on fccReconstruction file

.travis-ci.d/compile_and_test.sh
- CI: added -Werror flag to CI compilation
=> Add Werror to CI

clicConfig/clicReconstruction.xml, fcceeConfig/fccReconstruction.xml
- CLIC: beam sizes from CDR
- FCCee: beam sizes from FCC Week 2018
=> clicReconstruction and fccReconstruction: fixed B field and beam sizes in vertexing

fcceeConfig/fccReconstruction.xml
- fccReconstruction:: JetClusteringAndRefiner: B field changed from 4 T to 2 T
=> [fccReconstruction]: JetClusteringAndRefiner: fixed magnetic field value

clicConfig/CalibrationPandoraSettings/PandoraSettingsPhotonTraining.xml, fcceeConfig/CalibrationPandoraSettings/PandoraSettingsPhotonTraining.xml
- add PandoraSettingsPhotonTraining.xml needed for calorimeter calibration service
=> add PandoraSettingsPhotonTraining.xml

clicConfig/clic_steer.py, fcceeConfig/fcc_steer.py
- CLICSimulation: set physics.decays = False
- FCCSimulation: set physics.decays = False
=> Simulation: disable adding decays

clicConfig/clicReconstruction.xml, fcceeConfig/fccReconstruction.xml
- Update xml file with z cut on ConformalTracking (https://github.com/iLCSoft/ConformalTracking/pull/53)
=> Include z slope cut and timing debugs

.travis-ci.d/compile_and_test.sh, .travis.yml
Just use the installed release instead of nightly
=> [v02-04] CI: base on this release

Tracking/include/ClicEfficiencyCalculator.h, Tracking/src/ClicEfficiencyCalculator.cc
- Add track purity in perfTree for tracking validation (already present in purTree)
=> Add purity in perfTree

Tests/CMakeLists.txt
- FCCee tests: change to new location of CLD in k4geo
The tests would fail, but without the change I cannot deploy the new stacks, so merging this now.
=> FCCee tests: change to new location of CLD

Tests/bin/MarlinTests.sh, Tests/bin/Profiler.sh, Tests/bin/ValgrindTests.sh
- Tests: add "=" to possible MARLIN_DLL paths as the newer key4hep nightlies contain that character
=> Tests: add "=" to possible lib path

Tests/CMakeLists.txt
- Tests: adapt, following the renaming of lcgeo to k4geo
=> Tests: renamed lcgeo to k4geo
