iLCSoft/CLICPerformance

- examples/PandoraSettings/PandoraSettingsDefault.xml
- examples/clicReconstruction.xml
update PandoraSettings file, reflecting changes in the MuonClusterAssociation algorithm.
Update in the reconstruction steering file: 
change the direction of the fit in TruthTracking for improved performance for models CLIC_o3_v07 and CLIC_o3_v08
> Steer update 170202

- examples/clicReconstruction.xml
Until we get rid of this parameter in ConformalTracking we need to set it to the correct value.
Please take note: @webermat @eleogran @simoniel
> ConformalTracking: correct the DecoderString for latest CLIC models

- Tracking/src/ClicEfficiencyCalculator.cc
- Tracking/src/HitResiduals.cc
- Tracking/src/TrackChecker.cc
to address issue https://github.com/iLCSoft/LCIO/issues/4
> Replace ILDCellID0 with LCTrackerCellID

- examples/PandoraSettings/PandoraSettingsDefault.xml
- Reconstruction::MuonReconstruction change number of required layers for muon identification to reflect smaller number of layers in the muon system. Increases Muon ID efficiency
> Reconstruction::MuonReco: adapt parameters to smaller number of layers

- Tracking/src/ClicEfficiencyCalculator.cc
The logic behind this code is not clear to me.  Has this ever worked correctly? Are these branches used in some  of the macros making plots?
- ClicEfficiencyCalculator: Fix #18 , comment code storing information when particle not reconstructed, however some of that information is not aggregated beforehand so there was a crash
> ClicEfficiencyCalculator: comment unusable code

- CMakeLists.txt
- Tests/CMakeLists.txt
- examples/clicReconstruction.xml
- source/Conditions/include/CLICRecoConfig.h
- source/Conditions/src/CLICRecoConfig.cc
Needs: ilcsoft/Marlin#11; contains #16 and thus needs ilcsoft/Overlay#6.
This would allow one to chose which reconstruction to run based on command line arguments (or less changes in the steering file)
Command line:
```
Marlin clicReconstruction.xml  --Config.Tracking=Truth  --Config.Overlay=3TeV
```
Steering File
```
<parameter name="Tracking" type="String"> Truth </parameter>
<parameter name="Overlay" type="String"> False </parameter>
```
- Add CLICRecoConfig processor to chose which configuration to use for reconstruction: truth conformal tracking, if and which overlay
> [Request for Comments] Allow steering of reconstruction

- Tracking/include/HitResiduals.h
- Tracking/src/HitResiduals.cc
* HitResiduals: replaced 'subdet' with 'system' in the call to the encoding string (otherwise the processor won't work) and added the 'side' information needed to propagateToLayer when hits are in the endcaps.
> Fixes for HitResidual Processor

- CMakeLists.txt
- Tests/CMakeLists.txt
- Tests/bin/ValgrindTests.sh
- etc/extra-root.supp
- tests running valgrind:
By default uses valgrind from /cvmfs/sft
to run:
`ctest -C valgrind -R _testName_`
See test names via `ctest -C valgrind -N`
- Added option to run tests for CLIC_o2_v04 model for faster debugging 
E.g.: `ctest -C o2_v04 -R o2_v04 -E valgrind`
needs special steering file without GlobalTrackerReadoutID specified
- Add suppressions file for valgrind to use in addition to root suppressions file for uninitialised member in a TObject
> add tests running Valgrind

- Tracking/src/ClicEfficiencyCalculator.cc
- Tracking/src/HitResiduals.cc
- Tracking/src/TrackChecker.cc
- Ensure that histograms and trees are written only to their folder in the RootFile. AIDAProcessor already writes the outputs so we don't have to as well
- TrackChecker: beautify fit output by naming parameters. Fix issue with unnormalised gauss function
> Fix problem with root files

- Tests/CMakeLists.txt
- examples/clicReconstruction.xml
For running via the production system I need the two output processors, and something in the file names with `_REC`  and `_DST`
- Reconstruction: Add REC/DST OutputProcessors
- Reconstruction: Change default name of the output file to Output_REC.slcio and Output_DST.slcio instead of sitracks.slcio
- Reconstruction: Change name of `SelectedPandoraPFO` collections. Instead of `SelectedPandoraPFANewPFO` collections
> Reconstruction: Add Output_REC/DST processors

- Tracking/src/HitResiduals.cc
- examples/clicReconstruction.xml
- HitResiduals: protect against missing trackstate
- HitResiduals: use AtIP instead of AtFirstHit
- Reconstruction: fix typo in parameter value for RefitFinal (inconsequential as using default value anyway)
- Reconstruction: use SiTracks_Refitted for HitResiduals and CLICEfficiencyCalculator
> Fixes for hit residuals, reconstruction

- Tracking/src/ClicEfficiencyCalculator.cc
- ClicEfficiencyCalculator: updated ILDLike cuts to accept unique hits only, i.e. hits from different subdetector layers, as in the default NHits cuts
> ClicEfficiencyCalculator: updated ILDLike cuts

- Tracking/src/ClicEfficiencyCalculator.cc
- ClicEfficiencyCalculator: enabled simpleOutput tree (very important for efficiency plots)
> ClicEfficiencyCalculator: enabled simpleOutput, default: true

- Tracking/include/ClicEfficiencyCalculator.h
- Tracking/src/ClicEfficiencyCalculator.cc
- examples/clicReconstruction.xml
- ClicEfficiencyCalculator: added 'isSignal' flag for MCPhysicsParticles
- MCPhysicsParticles collection is the output of the Overlay Processor
- in case of no overlay, the MCParticle collection is used instead
- clicReconstruction.xml: MCPhysicsParticles collection as input
> ClicEfficiencyCalculator: added 'isSignal' flag for MCPhysicsParticles

- Tracking/src/ClicEfficiencyCalculator.cc
- ClicEfficiencyCalculator: fixed storing of track purity: now done with a std::list<std::pair<MCParticle*,double>>, which stores the MCParticle associated to the track and the track purity
> ClicEfficiencyCalculator: fixed storing of track purity

- examples/fccReconstruction.xml
- `clicReconstruction.xml`: removed unused processor (`DDCellsAutomatonMV`)
- `fccReconstruction.xml`: new steering file for reconstruction with the FCCee detector (conformal tracking parameters are different than for CLIC)
> Updated reconstruction steering files

- Tests/CMakeLists.txt
- Tests/bin/Profiler.sh
- examples/clicReconstruction.xml
- CLIC Reconstruction:
- Add SiTracks_Refitted to DST Output, add LumiCal and BeamCal Cluster and RecoParticle to DST Output
- Note that BeamCalReconstruction output collections have changed names to be consistent with LumiCalOutput
- Add new options to ConformalTracking (iLCSoft/ConformalTracking#28, iLCSoft/ConformalTracking#29)
- add call for running vtune on reconstruction (only works in CERN intranet)
`ctest  -C PROF -R t_test_CLIC_o3_v13_reco_conformal_zuds_overlay_profile -V`
> CLIC Reconstruction: dstOutput, tests, pfo selector

- examples/clicReconstruction.xml
- source/Conditions/include/CLICRecoConfig.h
- source/Conditions/src/CLICRecoConfig.cc
- Refactoring Config Processor: allow extending options via parameters, easier to add new options
- Add 380GeV BeamCalBackground file based on 380GeV L*=6m (http://clic-beam-beam.web.cern.ch/clic-beam-beam/380gev_l6_bx8mm.html)
- Waiting for ilcsoft/Marlin#28 to be deployed to optimize selection of processors, which makes the Config processor obsolete and command line arguments would would be `--constant....` instead of `--Config...`
> Add configuration for different BeamCal Reco energies (380GeV)

- examples/clicReconstruction.xml
- examples/fccReconstruction.xml
- Updated steering files clicReconstruction.xml and fccReconstruction.xml
- Single point resolutions in the tracker (inner and outer, barrel and endcap): 7um x 90um
- all layers except 1st inner tracker endcap: still 5um x 5um
> Steering files: updated single point resolutions in trackers

- examples/clicReconstruction.xml
- Reconstruction: DST Files: add low energy Selected PFO collection
- Fix typo in LE_TightSelectedPandoraPFOs
> Reconstruction: add low energy pandora PFOs to DST files

- Tests/CMakeLists.txt
- examples/clicReconstruction.xml
- Use BeamCalReco for LumiCal reconstruction
- Merge Cluster collections and feed all to RecoMCTruthLiner
- Merge ReconstructedParticle collections and feed all o RecoMCTruthLinker
- Only gives physics particles to RecoMCTruthLinker
- Switch Tests to CLIC_o3_v14
> Reconstruction update: LumiCal Reco, RecoMCTruthLinker

- examples/clic_steer.py
- Simulation: add Lorentz boost for the crossing angle to clic_steer.py
> Simulation:  add lorentzboost

- examples/fccReconstruction.xml
- examples/fcc_steer.py
- source/Conditions/include/CLICRecoConfig.h
- **fcc_steer.py**: Lorentz boost set to 0.015 rad [NB: to be used on pairs files only if those have been produced without crossing angle. If this is not the case, set the Lorentz boost to 0.0]
- **fccReconstruction.xml**: adjusted Overlay parameters to FCCee (number of BX, Delta_t, integration time windows per subdetector, number of events to overlay = 1 -- not Poissonian -- given that the gen files from GuineaPig contain 1 evt per file) and removed BeamCalReco (not available for FCCee yet)
- **CLICRecoConfig.h**: added two options for FCCee background overlay (91GeV, 365GeV)
> Fcc steering files

- examples/clicReconstruction.xml
-  ClicReconstruction::Overlay: correct the eventsPerBX numbers for L*=6m overlay instances
> Overlay: fix number of events per bunch crossings

- examples/clicReconstruction.xml
- examples/fccReconstruction.xml
Adding the parameters introduced in ilcsoft/ConformalTracking#34
- CLICReco: ConformalTracking: add the new parameters for collection names in VXDBarrel/Endcap and MainTracker
- FCCReco: ConformalTracking: add the new parameters for collection names in VXDBarrel/Endcap and MainTracker
> Reco: add parameters for collection names

- Tests/CMakeLists.txt
- examples/clicReconstruction.xml
- examples/fccReconstruction.xml
- Reconstruction: add all parameters for DDMarlinPandora, fixes #66 
- Reconstruction: DDMarlinPandora increase D0 and Z0 cut offs
- Reconstruction: Add MCPhysicsParticles to DST output file
Todo:
> Reconstruction: add parameters to DDMarlinPandora

- clicConfig/clicReconstruction.xml
- Clic Reconstruction: Update the Low Energy timing cuts: the variables “HcalBarrelLoose(/Tight)TimingCut” are now set consistently with the loose (tight) timing cuts imposed on neutral hadrons.
> Update LE timing cuts for HCalBarrel

- clicConfig/clicReconstruction.xml
- fcceeConfig/fccReconstruction.xml
- ConformalTracking: Set pT threshold to run extendHighPt as introduced in iLCSoft/ConformalTracking#42
- Added to both clic and fccee steering files
> Steering files: added pt cut to enable extendHighPt

- Visualisation/FCCee_o1_v03_CED/ECalBarrel_o2_v01_03.xml
- Visualisation/FCCee_o1_v03_CED/ECalEndcap_o2_v01_03.xml
- Visualisation/FCCee_o1_v03_CED/FCCee_o1_v03_CED.xml
- Visualisation/FCCee_o1_v03_CED/HCalBarrel_o1_v01_01.xml
- Visualisation/FCCee_o1_v03_CED/HCalEndcap_o1_v01_01.xml
- Visualisation/FCCee_o1_v03_CED/InnerTracker_o2_v01_01.xml
- Visualisation/FCCee_o1_v03_CED/LumiCal_o3_v02_02.xml
- Visualisation/FCCee_o1_v03_CED/Materials_v01.xml
- Visualisation/FCCee_o1_v03_CED/Solenoid_o1_v01_02.xml
- Visualisation/FCCee_o1_v03_CED/Vertex_o2_v02_01.xml
- Visualisation/FCCee_o1_v03_CED/Vertex_o4_v05.xml
- Visualisation/FCCee_o1_v03_CED/YokeBarrel_o1_v01_02.xml
- Visualisation/FCCee_o1_v03_CED/YokeEndcap_o1_v01_02.xml
- Visualisation/FCCee_o1_v03_CED/ced2go-template-DD4.xml
- Visualisation/FCCee_o1_v03_CED/elements.xml
- Visualisation/FCCee_o1_v03_CED/materials.xml
- Add `FCCee_o1_v03_CED` model into Visualisation folder. Model only suitable for event display not for simulation!
- example usage: `ced2go -t ced2go-template-DD4.xml -d FCCee_o1_v03_CED.xml data/REC/00010521/000/Z_uds_rec_10521_105.slcio`
- Final colour scheme still has to be decided by FCCee people
> CED model for FCCee

- Tracking/src/ClicEfficiencyCalculator.cc
- In the tree the nHitsMC must be the number of hits that are reconstructed and that belong to the same particle. 
> Use trackHits to compute MC hits in tree

- clicConfig/clicReconstruction.xml
> ClicReco: keep vertex reconstruction collections in DST file

- Visualisation/CLIC_o3_v06_CED/CLIC_o3_v06_CED.xml
- Visualisation/CLIC_o3_v06_CED/InnerTracker_o2_v01_01.xml
- Visualisation/CLIC_o3_v06_CED/ced2go-template-DD4.xml
- Enable energy coloring in visualization in CLIC visualization template and use new colors for the event display
requires iLCSoft/CEDViewer#9
> Enable energy coloring in visualization

- clicConfig/clicReconstruction.xml
- fcceeConfig/fccReconstruction.xml
- Add final minimum number of track clusters, after KF and set it to 4, needs ilcsoft/conformaltracking#52
- Include maximum number of track hits to try the inverted fit and set it to 0
> Add minimum number of cluster for tracks

- Flavour_tagging/vtx_makentp.xml
- Tests/CMakeLists.txt
- clicConfig/clicReconstruction.xml
- fcceeConfig/fccReconstruction.xml
- CLIC/FCC Reconstruction: add default values for lcfiplus processors, fix inconsistencies
- CLIC/FCC Reconstruction: rename collections from vertexing and flavourtagging
> Update LCFIPLus parameters and collection names

- clicConfig/clic_steer.py
- fcceeConfig/fcc_steer.py
- Explicitly list the rejected PDG codes for simulation
- DD4hep default did not reject Higgs PDG code 25
> Explicitly list the rejected PDG codes for simulation

- clicConfig/clicReconstruction.xml
- fcceeConfig/fccReconstruction.xml
- CLICReconstruction/FCCReconstruction: ConformalTracking+Refit: 
- Set the number of minimum hits on a track to 3 after the fit to recover efficiency loss seen in the case of single isolated muons. Previously this was set to 4 to reduce the number of fakes in the complex events which is still acceptable using a threshold at 3 hits.
This can be seen in the following efficiency plots:
[single muons - efficiency]
minimum number of hits on track = 3 : [eff_vs_theta_minNhits3.pdf](https://github.com/iLCSoft/CLICPerformance/files/3277293/eff_vs_theta_minNhits3-eps-converted-to.pdf)
minimum number of hits on track = 4 : [eff_vs_theta_minNhits4.pdf](https://github.com/iLCSoft/CLICPerformance/files/3277294/eff_vs_theta_minNhits4-eps-converted-to.pdf)
[3TeV ttbar …
> MinClustersOnTrackAfterFit set to 3

- clicConfig/clicReconstruction.xml
- fcceeConfig/fccReconstruction.xml
- FCC/ClicReco: add optional parameters for Output_REC, Output_DST so that they can be overwritten via the command line
> FCC/ClicReco: add optional parameters for Output_REC, Output_DST

- Tracking/src/ClicEfficiencyCalculator.cc
- ClicEfficiencyCalculator: fixed m_vec_is_reconstructed branch for not reconstructed tracks in trackTree, fixes #116 
> ClicEfficiencyCalculator: fixed is_reco false in trackTree

- clicConfig/clic_steer.py
- fcceeConfig/fcc_steer.py
- DDSim Steer: fix spelling of ClassicalRK4 for magnetic field stepper, this is also the geant4 default
> DDSim: correct the name for the field stepper

- clicConfig/clic_steer.py
- fcceeConfig/fcc_steer.py
- clic_steer, fcc_steer: use g4units instead of dropped SystemOfUnits
> DDSim steering files: drop use of deprecated (removed) units file

- Tracking/src/SkimSecondaryVertices.cc
- SkimSecondaryVertices: fixed mismatch in length units between dd4hep and lcio
- Uniformized with dd4hep::mm
> SkimSecondaryVertices: uniformized length units (dd4hep::mm)

- clicConfig/clicReconstruction.xml
- CLIC Reco: ConformalTracking: Set HighPTCut to 0
- According to a study on the conformal tracking fit for the ExtendTracks step, the quadratic term in the fit is not needed for the low-pT tracks. Results for ttbar w/o and w/ overlay shows unchanged level of tracking efficiency, slightly increase of fakerate, and reduction CPU time of 13%. Full set of results [here](https://indico.cern.ch/event/848916/contributions/3567053/attachments/1909256/3154418/EricaBrondolin_20190917_LowPtStudies.pdf).
> HighPTCut set to 0.0 in CT ExtendTracks 

- Calorimetry/include/JetAnalyzer.h
- Calorimetry/include/TrueMCintoRecoForJets.h
- Calorimetry/src/JetAnalyzer.cc
- Calorimetry/src/TrueMCintoRecoForJets.cc
- Calorimetry/testCalibJetStudies.xml
- 1. JetAnalyzer for Jet and missing (transverse) energy studies
- 2. TrueMCintoRecoForJets MCParticle and ReconstructedParticle for jets selector, giving functionality to select different input particles
a) options for MC particles: stable particles, including all neutrinos, including all neutrinos from hadronic decays
b) remove reconstructed particles after angular matching to leptons from vector boson decays
> Jet study analyzer - for discussion

- clicConfig/clicReconstruction.xml
- fcceeConfig/fccReconstruction.xml
- ClicReconstruction: Reduce ConformalTracking.TooManyTracks to 100k from 500k
- FccReconstruction: Reduce ConformalTracking.TooManyTracks to 100k from 500k
> Reconstruction: reduce too many tracks limit to 100k

- Tracking/include/ClicEfficiencyCalculator.h
- Tracking/src/ClicEfficiencyCalculator.cc
- clicConfig/clicReconstruction.xml
- New cuts for new definitions of reconstructability added to ClicEfficiencyCalculator
- Cut "AnyGenStatus" is optimized for charginos (no requirement on number of hits and on stability)
- Cut "AnyGenStatusLowPt" is optimized for soft pions from chargino decays (like "AnyGenStatus" but without requirement on pt)
> New definitions of reconstructability

- clicConfig/clicReconstruction.xml
- fcceeConfig/fccReconstruction.xml
- Adapt `fcc-` and `clicReconstruction.xml` according to the [PR#45 in MarlinTrkProcessors](https://github.com/iLCSoft/MarlinTrkProcessors/pull/45)
- `mergeSplitTracks` is set to true in the case of `clicReconstruction.xml`
> Adapt xml files to have correct parameters in ClonesAndSplitTracksFinder

- clicConfig/clicReconstruction.xml
- clicConfig/clic_steer.py
- fcceeConfig/fccReconstruction.xml
- fcceeConfig/fcc_steer.py
- CLIC Simulation: change the path to the particle.tbl file
- FCC Simulation: change the path to the particle.tbl file
- CLIC Reconstruction: change path of default detector and input file, fixes #131 
- FCC Reconstruction: change path of default  input file, fixes #131 
> Clic steer

- clicConfig/clicReconstruction.xml
- Fix naming for MergeClusters collection name for LumiCalClusters
> Fix LumiCalCLusters name in MergeClusters

- .github/workflows/linux.yml
- Tests/CMakeLists.txt
- Tests: Add dependencies for FCCee reco tests
> Tests: add test dependency for FCCee tests
